# Generated by Django 4.1.6 on 2023-02-09 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=20, verbose_name='Shop Name')),
                ('order_count', models.IntegerField(default=0, verbose_name='Order Count')),
                ('delivered_count', models.IntegerField(default=0, verbose_name='Number of orders delivered')),
                ('pending_count', models.IntegerField(default=0, verbose_name='Number of pending delivery orders')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Delivery Pending', 'Delivery pending'), ('Order Delivered', 'Order delivered')], default='Delivery Pending', max_length=16)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.shops')),
            ],
        ),
    ]
